AGENTS = [
    {
        "name": "LexAgent",
        "nickname": "렉스",
        "desc": "개인정보 법령 RAG 분석",
        "detail": "법령 데이터 기반 질의응답 및 조항 분석",
        "port": 9001,
        "path": r"C:\Users\USER\Desktop\Project Agent\LexAgent",
        "icon": "⚖️",
        "color": "#4F8EF7",
    },
    {
        "name": "PolicyAgent",
        "nickname": "폴리",
        "desc": "개인정보 처리방침 분석",
        "detail": "처리방침 문서 검토 및 체크리스트 자동화",
        "port": 9002,
        "path": r"C:\Users\USER\Desktop\Project Agent\PolicyAgent",
        "icon": "🔐",
        "color": "#43C59E",
    },
    {
        "name": "GosiAgent",
        "nickname": "고시",
        "desc": "고시 수집 및 알림",
        "detail": "행정 고시 자동 수집 및 실시간 알림",
        "port": 9003,
        "path": r"C:\Users\USER\Desktop\Project Agent\GosiAgent",
        "icon": "🏛️",
        "color": "#F7934F",
    },
    {
        "name": "ModelTLab",
        "nickname": "모델랩",
        "desc": "AI 모델 파인튜닝·채팅 테스트",
        "detail": "파인튜닝 모델 실험 및 채팅 인터페이스",
        "port": 3010,
        "path": r"C:\Users\USER\Desktop\Project Agent\ModelTLab",
        "icon": "🧫",
        "color": "#D4956A",
    },
    {
        "name": "gov_kr",
        "nickname": "고브",
        "desc": "건축물대장 조회",
        "detail": "건축물대장 자동 조회 및 정보 확인",
        "port": 1001,
        "path": r"C:\Users\USER\Desktop\Project Agent\gov_kr",
        "icon": "🏢",
        "color": "#6C63FF",
    },
    {
        "name": "SonarGuard",
        "nickname": "소나",
        "desc": "코드 취약점 스캐너",
        "detail": "정적 분석 기반 코드 보안 취약점 스캐닝",
        "port": 2001,
        "path": r"C:\Users\USER\Desktop\Project Agent\local_sonar_test",
        "icon": "🛡️",
        "color": "#E05C4A",
    },
    {
        "name": "AIpartner(세무)",
        "nickname": "삼일PWC",
        "desc": "세무 관련 법안 분석",
        "detail": "세무법안 관련 수집 및 분석",
        "port": 9101,
        "path": r"C:\Users\USER\Desktop\Project Agent\ProptierAI",
        "icon": "🤝",
        "color": "#8B5CF6",
    },
    {
        "name": "MarketInsight",
        "nickname": "마인",
        "desc": "시장 트렌드 분석",
        "detail": "브랜드 키워드, 트렌드, 경쟁사 동향 분석",
        "port": 3100,
        "path": r"C:\Users\USER\Desktop\Project Agent\MarketInsight",
        "icon": "📈",
        "color": "#00B8A9",
    },
    {
        "name": "Proptier AI News",
        "nickname": "프니",
        "desc": "부동산 AI 뉴스",
        "detail": "부동산 뉴스 수집·브리핑·검색 및 PDF 보고서 생성",
        "port": 7000,
        "path": r"C:\Users\USER\Desktop\Project Agent\hana_p",
        "icon": "🏠",
        "color": "#FFA41B",
    },
    {
        "name": "DailyBot(6F)",
        "nickname": "데일리봇",
        "desc": "6층 일일 업무 봇",
        "detail": "6층 일일 업무 처리 및 알림 봇",
        "port": 7001,
        "path": r"C:\Users\USER\Desktop\Project Agent\DailyBot",
        "icon": "📅",
        "color": "#FFC93C",
    },
]
